worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    client_max_body_size 50m;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript
               application/xml text/xml application/x-yaml;

    # Upstreams
    upstream odoo {
        server odoo:8069;
    }
    upstream odoo_chat {
        server odoo:8072;
    }

    include conf.d/*.conf;
}
